#!/usr/bin/env bash

BLUE="\033[0;34m"
NOCOLOR="\033[0m"

echo -e "${BLUE}jupyter nbconvert --to interact $@ ${NOCOLOR}"
jupyter nbconvert --to interact $@

echo
echo -e "${BLUE}Done! You may now open the generated HTML file(s) in your web browser.${NOCOLOR}"
